version: '3'
volumes:
  finaldb_01:
services:
  database:
    image: "postgres:10-alpine"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: hadi
      POSTGRES_PASSWORD: 123456
      PGPASSWORD: 123456
      POSTGRES_DB: final_01
      PGDATA: /final_01
    volumes:
      - finaldb_01:/final_01
  cache:
    image: "memcached:alpine"
    ports:
      - 11211:11211
  broker:
    image: "rabbitmq:alpine"
    hostname: "final_broker"
    ports:
      - 5672:5672