# Generated by Django 3.2.8 on 2021-10-06 07:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('logo', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('employees_count', models.PositiveIntegerField(default=1, verbose_name='number of employees')),
                ('repr_name', models.CharField(max_length=200, verbose_name='name of representative')),
                ('repr_num', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='invalid entry', regex='^09(1[0-9]|3[1-9]|2[1-9]0[1-9])-?[0-9]{3}-?[0-9]{4}')], verbose_name='phone number of representative')),
                ('repr_email', models.EmailField(max_length=254, verbose_name='Email of representative')),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='registration date')),
                ('date_registered_jalali', django_jalali.db.models.jDateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name of product')),
                ('description', models.TextField(blank=True, help_text='technical description of product', verbose_name='Description')),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='registration date of the Product')),
                ('date_registered_jalali', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user responsible for registration')),
            ],
            options={
                'verbose_name_plural': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='technical description', verbose_name='Description')),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('taxable', models.BooleanField(default=True, help_text='Is product subjected to taxation?')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity in stock')),
                ('catalogue_image', models.ImageField(blank=True, upload_to='', verbose_name='catalogue image')),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='registration date')),
                ('date_registered_jalali', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='registration date')),
                ('downstream_product', models.ManyToManyField(blank=True, to='analyse.Product', verbose_name='Downstream Products')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user responsible for registration')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.product')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_products',
            field=models.ManyToManyField(blank=True, to='analyse.Product'),
        ),
        migrations.AddField(
            model_name='organization',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user responsible for registration'),
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('name', 'user')},
        ),
    ]
