# Generated by Django 3.2.8 on 2021-10-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationProduct',
        ),
    ]
