# Generated by Django 3.2.8 on 2021-10-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0003_organizationproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_products',
            field=models.ManyToManyField(blank=True, through='analyse.OrganizationProduct', to='analyse.Product'),
        ),
    ]
