# Generated by Django 3.2.8 on 2021-10-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0005_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
