# Generated by Django 3.2.8 on 2021-10-06 09:05

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date Registered')),
                ('date_registered_jalali', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('CREATED', 'quote created'), ('FINALISED', 'quote finalised')], max_length=100, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user responsible for registration')),
            ],
            options={
                'verbose_name_plural': 'quotes',
                'ordering': ['-date_registered'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(100)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analyse.stockproduct')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followup.quote')),
            ],
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date Registered')),
                ('date_registered_jalali', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('report', models.TextField(verbose_name='followup report')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user responsible for registration')),
            ],
            options={
                'verbose_name_plural': 'followups',
                'ordering': ['-date_registered'],
            },
        ),
    ]
